[package]
name = "shadcn-ui-yew-checkbox"
description = "Yew port of shadcn/ui Checkbox."
homepage = "https://shadcn-ui.rustforweb.org/components/checkbox.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tailwind_fuse.workspace = true
yew.workspace = true
yew-struct-component.workspace = true
yew-style.workspace = true
web-sys.workspace = true

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils", features = ["yew-testing"] }
wasm-bindgen-test = { workspace = true }