[package]
name = "shadcn"
description = "Rust port of shadcn CLI."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.4", features = ["cargo", "derive"] }
log.workspace = true
reqwest = { version = "0.12.4", features = ["gzip", "json"] }
serde.workspace = true
serde_json.workspace = true
spinners = "4.1.1"
tokio.workspace = true
toml = "0.9.0"
