[package]
name = "shadcn-ui-leptos-select"
description = "Leptos port of shadcn/ui Select."
homepage = "https://shadcn-ui.rustforweb.org/components/select.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tailwind_fuse = { workspace = true, features = ["variant"] }
leptos = { workspace = true, features = ["ssr"] }
leptos-node-ref.workspace = true
leptos-struct-component.workspace = true
leptos-style.workspace = true
web-sys.workspace = true

[features]
default = []
new_york = []

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils"}
wasm-bindgen-test = { workspace = true }
