use std::{collections::HashMap, sync::LazyLock};

use crate::schema::Mode;

pub struct BaseColor {
    pub name: String,
    pub label: String,
    pub active_color: HashMap<Mode, String>,
    pub css_vars: HashMap<Mode, HashMap<String, String>>,
}

pub static BASE_COLORS: LazyLock<Vec<BaseColor>> = LazyLock::new(|| {
    vec![
        BaseColor {
            name: "zinc".into(),
            label: "Zinc".into(),
            active_color: HashMap::from([
                (Mode::Light, "240 5.9% 10%".into()),
                (Mode::Dark, "240 5.2% 33.9%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "240 10% 3.9%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "240 10% 3.9%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "240 10% 3.9%".into()),
                        ("primary".into(), "240 5.9% 10%".into()),
                        ("primary-foreground".into(), "0 0% 98%".into()),
                        ("secondary".into(), "240 4.8% 95.9%".into()),
                        ("secondary-foreground".into(), "240 5.9% 10%".into()),
                        ("muted".into(), "240 4.8% 95.9%".into()),
                        ("muted-foreground".into(), "240 3.8% 46.1%".into()),
                        ("accent".into(), "240 4.8% 95.9%".into()),
                        ("accent-foreground".into(), "240 5.9% 10%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "240 5.9% 90%".into()),
                        ("input".into(), "240 5.9% 90%".into()),
                        ("ring".into(), "240 5.9% 10%".into()),
                        ("radius".into(), "0.5rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "240 10% 3.9%".into()),
                        ("foreground".into(), "0 0% 98%".into()),
                        ("card".into(), "240 10% 3.9%".into()),
                        ("card-foreground".into(), "0 0% 98%".into()),
                        ("popover".into(), "240 10% 3.9%".into()),
                        ("popover-foreground".into(), "0 0% 98%".into()),
                        ("primary".into(), "0 0% 98%".into()),
                        ("primary-foreground".into(), "240 5.9% 10%".into()),
                        ("secondary".into(), "240 3.7% 15.9%".into()),
                        ("secondary-foreground".into(), "0 0% 98%".into()),
                        ("muted".into(), "240 3.7% 15.9%".into()),
                        ("muted-foreground".into(), "240 5% 64.9%".into()),
                        ("accent".into(), "240 3.7% 15.9%".into()),
                        ("accent-foreground".into(), "0 0% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "240 3.7% 15.9%".into()),
                        ("input".into(), "240 3.7% 15.9%".into()),
                        ("ring".into(), "240 4.9% 83.9%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "slate".into(),
            label: "Slate".into(),
            active_color: HashMap::from([
                (Mode::Light, "215.4 16.3% 46.9%".into()),
                (Mode::Dark, "215.3 19.3% 34.5%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "222.2 84% 4.9%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "222.2 84% 4.9%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "222.2 84% 4.9%".into()),
                        ("primary".into(), "222.2 47.4% 11.2%".into()),
                        ("primary-foreground".into(), "210 40% 98%".into()),
                        ("secondary".into(), "210 40% 96.1%".into()),
                        ("secondary-foreground".into(), "222.2 47.4% 11.2%".into()),
                        ("muted".into(), "210 40% 96.1%".into()),
                        ("muted-foreground".into(), "215.4 16.3% 46.9%".into()),
                        ("accent".into(), "210 40% 96.1%".into()),
                        ("accent-foreground".into(), "222.2 47.4% 11.2%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "210 40% 98%".into()),
                        ("border".into(), "214.3 31.8% 91.4%".into()),
                        ("input".into(), "214.3 31.8% 91.4%".into()),
                        ("ring".into(), "222.2 84% 4.9%".into()),
                        ("radius".into(), "0.5rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "222.2 84% 4.9%".into()),
                        ("foreground".into(), "210 40% 98%".into()),
                        ("card".into(), "222.2 84% 4.9%".into()),
                        ("card-foreground".into(), "210 40% 98%".into()),
                        ("popover".into(), "222.2 84% 4.9%".into()),
                        ("popover-foreground".into(), "210 40% 98%".into()),
                        ("primary".into(), "210 40% 98%".into()),
                        ("primary-foreground".into(), "222.2 47.4% 11.2%".into()),
                        ("secondary".into(), "217.2 32.6% 17.5%".into()),
                        ("secondary-foreground".into(), "210 40% 98%".into()),
                        ("muted".into(), "217.2 32.6% 17.5%".into()),
                        ("muted-foreground".into(), "215 20.2% 65.1%".into()),
                        ("accent".into(), "217.2 32.6% 17.5%".into()),
                        ("accent-foreground".into(), "210 40% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "210 40% 98%".into()),
                        ("border".into(), "217.2 32.6% 17.5%".into()),
                        ("input".into(), "217.2 32.6% 17.5%".into()),
                        ("ring".into(), "212.7 26.8% 83.9".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "stone".into(),
            label: "Stone".into(),
            active_color: HashMap::from([
                (Mode::Light, "25 5.3% 44.7%".into()),
                (Mode::Dark, "33.3 5.5% 32.4%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "20 14.3% 4.1%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "20 14.3% 4.1%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "20 14.3% 4.1%".into()),
                        ("primary".into(), "24 9.8% 10%".into()),
                        ("primary-foreground".into(), "60 9.1% 97.8%".into()),
                        ("secondary".into(), "60 4.8% 95.9%".into()),
                        ("secondary-foreground".into(), "24 9.8% 10%".into()),
                        ("muted".into(), "60 4.8% 95.9%".into()),
                        ("muted-foreground".into(), "25 5.3% 44.7%".into()),
                        ("accent".into(), "60 4.8% 95.9%".into()),
                        ("accent-foreground".into(), "24 9.8% 10%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "60 9.1% 97.8%".into()),
                        ("border".into(), "20 5.9% 90%".into()),
                        ("input".into(), "20 5.9% 90%".into()),
                        ("ring".into(), "20 14.3% 4.1%".into()),
                        ("radius".into(), "0.95rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "20 14.3% 4.1%".into()),
                        ("foreground".into(), "60 9.1% 97.8%".into()),
                        ("card".into(), "20 14.3% 4.1%".into()),
                        ("card-foreground".into(), "60 9.1% 97.8%".into()),
                        ("popover".into(), "20 14.3% 4.1%".into()),
                        ("popover-foreground".into(), "60 9.1% 97.8%".into()),
                        ("primary".into(), "60 9.1% 97.8%".into()),
                        ("primary-foreground".into(), "24 9.8% 10%".into()),
                        ("secondary".into(), "12 6.5% 15.1%".into()),
                        ("secondary-foreground".into(), "60 9.1% 97.8%".into()),
                        ("muted".into(), "12 6.5% 15.1%".into()),
                        ("muted-foreground".into(), "24 5.4% 63.9%".into()),
                        ("accent".into(), "12 6.5% 15.1%".into()),
                        ("accent-foreground".into(), "60 9.1% 97.8%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "60 9.1% 97.8%".into()),
                        ("border".into(), "12 6.5% 15.1%".into()),
                        ("input".into(), "12 6.5% 15.1%".into()),
                        ("ring".into(), "24 5.7% 82.9%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "gray".into(),
            label: "Gray".into(),
            active_color: HashMap::from([
                (Mode::Light, "220 8.9% 46.1%".into()),
                (Mode::Dark, "215 13.8% 34.1%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "224 71.4% 4.1%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "224 71.4% 4.1%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "224 71.4% 4.1%".into()),
                        ("primary".into(), "220.9 39.3% 11%".into()),
                        ("primary-foreground".into(), "210 20% 98%".into()),
                        ("secondary".into(), "220 14.3% 95.9%".into()),
                        ("secondary-foreground".into(), "220.9 39.3% 11%".into()),
                        ("muted".into(), "220 14.3% 95.9%".into()),
                        ("muted-foreground".into(), "220 8.9% 46.1%".into()),
                        ("accent".into(), "220 14.3% 95.9%".into()),
                        ("accent-foreground".into(), "220.9 39.3% 11%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "210 20% 98%".into()),
                        ("border".into(), "220 13% 91%".into()),
                        ("input".into(), "220 13% 91%".into()),
                        ("ring".into(), "224 71.4% 4.1%".into()),
                        ("radius".into(), "0.35rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "224 71.4% 4.1%".into()),
                        ("foreground".into(), "210 20% 98%".into()),
                        ("card".into(), "224 71.4% 4.1%".into()),
                        ("card-foreground".into(), "210 20% 98%".into()),
                        ("popover".into(), "224 71.4% 4.1%".into()),
                        ("popover-foreground".into(), "210 20% 98%".into()),
                        ("primary".into(), "210 20% 98%".into()),
                        ("primary-foreground".into(), "220.9 39.3% 11%".into()),
                        ("secondary".into(), "215 27.9% 16.9%".into()),
                        ("secondary-foreground".into(), "210 20% 98%".into()),
                        ("muted".into(), "215 27.9% 16.9%".into()),
                        ("muted-foreground".into(), "217.9 10.6% 64.9%".into()),
                        ("accent".into(), "215 27.9% 16.9%".into()),
                        ("accent-foreground".into(), "210 20% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "210 20% 98%".into()),
                        ("border".into(), "215 27.9% 16.9%".into()),
                        ("input".into(), "215 27.9% 16.9%".into()),
                        ("ring".into(), "216 12.2% 83.9%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "neutral".into(),
            label: "Neutral".into(),
            active_color: HashMap::from([
                (Mode::Light, "0 0% 45.1%".into()),
                (Mode::Dark, "0 0% 32.2%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "0 0% 3.9%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "0 0% 3.9%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "0 0% 3.9%".into()),
                        ("primary".into(), "0 0% 9%".into()),
                        ("primary-foreground".into(), "0 0% 98%".into()),
                        ("secondary".into(), "0 0% 96.1%".into()),
                        ("secondary-foreground".into(), "0 0% 9%".into()),
                        ("muted".into(), "0 0% 96.1%".into()),
                        ("muted-foreground".into(), "0 0% 45.1%".into()),
                        ("accent".into(), "0 0% 96.1%".into()),
                        ("accent-foreground".into(), "0 0% 9%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "0 0% 89.8%".into()),
                        ("input".into(), "0 0% 89.8%".into()),
                        ("ring".into(), "0 0% 3.9%".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "0 0% 3.9%".into()),
                        ("foreground".into(), "0 0% 98%".into()),
                        ("card".into(), "0 0% 3.9%".into()),
                        ("card-foreground".into(), "0 0% 98%".into()),
                        ("popover".into(), "0 0% 3.9%".into()),
                        ("popover-foreground".into(), "0 0% 98%".into()),
                        ("primary".into(), "0 0% 98%".into()),
                        ("primary-foreground".into(), "0 0% 9%".into()),
                        ("secondary".into(), "0 0% 14.9%".into()),
                        ("secondary-foreground".into(), "0 0% 98%".into()),
                        ("muted".into(), "0 0% 14.9%".into()),
                        ("muted-foreground".into(), "0 0% 63.9%".into()),
                        ("accent".into(), "0 0% 14.9%".into()),
                        ("accent-foreground".into(), "0 0% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "0 0% 14.9%".into()),
                        ("input".into(), "0 0% 14.9%".into()),
                        ("ring".into(), "0 0% 83.1%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "red".into(),
            label: "Red".into(),
            active_color: HashMap::from([
                (Mode::Light, "0 72.2% 50.6%".into()),
                (Mode::Dark, "0 72.2% 50.6%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "0 0% 3.9%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "0 0% 3.9%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "0 0% 3.9%".into()),
                        ("primary".into(), "0 72.2% 50.6%".into()),
                        ("primary-foreground".into(), "0 85.7% 97.3%".into()),
                        ("secondary".into(), "0 0% 96.1%".into()),
                        ("secondary-foreground".into(), "0 0% 9%".into()),
                        ("muted".into(), "0 0% 96.1%".into()),
                        ("muted-foreground".into(), "0 0% 45.1%".into()),
                        ("accent".into(), "0 0% 96.1%".into()),
                        ("accent-foreground".into(), "0 0% 9%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "0 0% 89.8%".into()),
                        ("input".into(), "0 0% 89.8%".into()),
                        ("ring".into(), "0 72.2% 50.6%".into()),
                        ("radius".into(), "0.4rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "0 0% 3.9%".into()),
                        ("foreground".into(), "0 0% 98%".into()),
                        ("card".into(), "0 0% 3.9%".into()),
                        ("card-foreground".into(), "0 0% 98%".into()),
                        ("popover".into(), "0 0% 3.9%".into()),
                        ("popover-foreground".into(), "0 0% 98%".into()),
                        ("primary".into(), "0 72.2% 50.6%".into()),
                        ("primary-foreground".into(), "0 85.7% 97.3%".into()),
                        ("secondary".into(), "0 0% 14.9%".into()),
                        ("secondary-foreground".into(), "0 0% 98%".into()),
                        ("muted".into(), "0 0% 14.9%".into()),
                        ("muted-foreground".into(), "0 0% 63.9%".into()),
                        ("accent".into(), "0 0% 14.9%".into()),
                        ("accent-foreground".into(), "0 0% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "0 0% 14.9%".into()),
                        ("input".into(), "0 0% 14.9%".into()),
                        ("ring".into(), "0 72.2% 50.6%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "rose".into(),
            label: "Rose".into(),
            active_color: HashMap::from([
                (Mode::Light, "346.8 77.2% 49.8%".into()),
                (Mode::Dark, "346.8 77.2% 49.8%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "240 10% 3.9%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "240 10% 3.9%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "240 10% 3.9%".into()),
                        ("primary".into(), "346.8 77.2% 49.8%".into()),
                        ("primary-foreground".into(), "355.7 100% 97.3%".into()),
                        ("secondary".into(), "240 4.8% 95.9%".into()),
                        ("secondary-foreground".into(), "240 5.9% 10%".into()),
                        ("muted".into(), "240 4.8% 95.9%".into()),
                        ("muted-foreground".into(), "240 3.8% 46.1%".into()),
                        ("accent".into(), "240 4.8% 95.9%".into()),
                        ("accent-foreground".into(), "240 5.9% 10%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "240 5.9% 90%".into()),
                        ("input".into(), "240 5.9% 90%".into()),
                        ("ring".into(), "346.8 77.2% 49.8%".into()),
                        ("radius".into(), "0.5rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "20 14.3% 4.1%".into()),
                        ("foreground".into(), "0 0% 95%".into()),
                        ("popover".into(), "0 0% 9%".into()),
                        ("popover-foreground".into(), "0 0% 95%".into()),
                        ("card".into(), "24 9.8% 10%".into()),
                        ("card-foreground".into(), "0 0% 95%".into()),
                        ("primary".into(), "346.8 77.2% 49.8%".into()),
                        ("primary-foreground".into(), "355.7 100% 97.3%".into()),
                        ("secondary".into(), "240 3.7% 15.9%".into()),
                        ("secondary-foreground".into(), "0 0% 98%".into()),
                        ("muted".into(), "0 0% 15%".into()),
                        ("muted-foreground".into(), "240 5% 64.9%".into()),
                        ("accent".into(), "12 6.5% 15.1%".into()),
                        ("accent-foreground".into(), "0 0% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "0 85.7% 97.3%".into()),
                        ("border".into(), "240 3.7% 15.9%".into()),
                        ("input".into(), "240 3.7% 15.9%".into()),
                        ("ring".into(), "346.8 77.2% 49.8%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "orange".into(),
            label: "Orange".into(),
            active_color: HashMap::from([
                (Mode::Light, "24.6 95% 53.1%".into()),
                (Mode::Dark, "20.5 90.2% 48.2%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "20 14.3% 4.1%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "20 14.3% 4.1%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "20 14.3% 4.1%".into()),
                        ("primary".into(), "24.6 95% 53.1%".into()),
                        ("primary-foreground".into(), "60 9.1% 97.8%".into()),
                        ("secondary".into(), "60 4.8% 95.9%".into()),
                        ("secondary-foreground".into(), "24 9.8% 10%".into()),
                        ("muted".into(), "60 4.8% 95.9%".into()),
                        ("muted-foreground".into(), "25 5.3% 44.7%".into()),
                        ("accent".into(), "60 4.8% 95.9%".into()),
                        ("accent-foreground".into(), "24 9.8% 10%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "60 9.1% 97.8%".into()),
                        ("border".into(), "20 5.9% 90%".into()),
                        ("input".into(), "20 5.9% 90%".into()),
                        ("ring".into(), "24.6 95% 53.1%".into()),
                        ("radius".into(), "0.95rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "20 14.3% 4.1%".into()),
                        ("foreground".into(), "60 9.1% 97.8%".into()),
                        ("card".into(), "20 14.3% 4.1%".into()),
                        ("card-foreground".into(), "60 9.1% 97.8%".into()),
                        ("popover".into(), "20 14.3% 4.1%".into()),
                        ("popover-foreground".into(), "60 9.1% 97.8%".into()),
                        ("primary".into(), "20.5 90.2% 48.2%".into()),
                        ("primary-foreground".into(), "60 9.1% 97.8%".into()),
                        ("secondary".into(), "12 6.5% 15.1%".into()),
                        ("secondary-foreground".into(), "60 9.1% 97.8%".into()),
                        ("muted".into(), "12 6.5% 15.1%".into()),
                        ("muted-foreground".into(), "24 5.4% 63.9%".into()),
                        ("accent".into(), "12 6.5% 15.1%".into()),
                        ("accent-foreground".into(), "60 9.1% 97.8%".into()),
                        ("destructive".into(), "0 72.2% 50.6%".into()),
                        ("destructive-foreground".into(), "60 9.1% 97.8%".into()),
                        ("border".into(), "12 6.5% 15.1%".into()),
                        ("input".into(), "12 6.5% 15.1%".into()),
                        ("ring".into(), "20.5 90.2% 48.2%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "green".into(),
            label: "Green".into(),
            active_color: HashMap::from([
                (Mode::Light, "142.1 76.2% 36.3%".into()),
                (Mode::Dark, "142.1 70.6% 45.3%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "240 10% 3.9%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "240 10% 3.9%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "240 10% 3.9%".into()),
                        ("primary".into(), "142.1 76.2% 36.3%".into()),
                        ("primary-foreground".into(), "355.7 100% 97.3%".into()),
                        ("secondary".into(), "240 4.8% 95.9%".into()),
                        ("secondary-foreground".into(), "240 5.9% 10%".into()),
                        ("muted".into(), "240 4.8% 95.9%".into()),
                        ("muted-foreground".into(), "240 3.8% 46.1%".into()),
                        ("accent".into(), "240 4.8% 95.9%".into()),
                        ("accent-foreground".into(), "240 5.9% 10%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "0 0% 98%".into()),
                        ("border".into(), "240 5.9% 90%".into()),
                        ("input".into(), "240 5.9% 90%".into()),
                        ("ring".into(), "142.1 76.2% 36.3%".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "20 14.3% 4.1%".into()),
                        ("foreground".into(), "0 0% 95%".into()),
                        ("popover".into(), "0 0% 9%".into()),
                        ("popover-foreground".into(), "0 0% 95%".into()),
                        ("card".into(), "24 9.8% 10%".into()),
                        ("card-foreground".into(), "0 0% 95%".into()),
                        ("primary".into(), "142.1 70.6% 45.3%".into()),
                        ("primary-foreground".into(), "144.9 80.4% 10%".into()),
                        ("secondary".into(), "240 3.7% 15.9%".into()),
                        ("secondary-foreground".into(), "0 0% 98%".into()),
                        ("muted".into(), "0 0% 15%".into()),
                        ("muted-foreground".into(), "240 5% 64.9%".into()),
                        ("accent".into(), "12 6.5% 15.1%".into()),
                        ("accent-foreground".into(), "0 0% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "0 85.7% 97.3%".into()),
                        ("border".into(), "240 3.7% 15.9%".into()),
                        ("input".into(), "240 3.7% 15.9%".into()),
                        ("ring".into(), "142.4 71.8% 29.2%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "blue".into(),
            label: "Blue".into(),
            active_color: HashMap::from([
                (Mode::Light, "221.2 83.2% 53.3%".into()),
                (Mode::Dark, "217.2 91.2% 59.8%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "222.2 84% 4.9%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "222.2 84% 4.9%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "222.2 84% 4.9%".into()),
                        ("primary".into(), "221.2 83.2% 53.3%".into()),
                        ("primary-foreground".into(), "210 40% 98%".into()),
                        ("secondary".into(), "210 40% 96.1%".into()),
                        ("secondary-foreground".into(), "222.2 47.4% 11.2%".into()),
                        ("muted".into(), "210 40% 96.1%".into()),
                        ("muted-foreground".into(), "215.4 16.3% 46.9%".into()),
                        ("accent".into(), "210 40% 96.1%".into()),
                        ("accent-foreground".into(), "222.2 47.4% 11.2%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "210 40% 98%".into()),
                        ("border".into(), "214.3 31.8% 91.4%".into()),
                        ("input".into(), "214.3 31.8% 91.4%".into()),
                        ("ring".into(), "221.2 83.2% 53.3%".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "222.2 84% 4.9%".into()),
                        ("foreground".into(), "210 40% 98%".into()),
                        ("card".into(), "222.2 84% 4.9%".into()),
                        ("card-foreground".into(), "210 40% 98%".into()),
                        ("popover".into(), "222.2 84% 4.9%".into()),
                        ("popover-foreground".into(), "210 40% 98%".into()),
                        ("primary".into(), "217.2 91.2% 59.8%".into()),
                        ("primary-foreground".into(), "222.2 47.4% 11.2%".into()),
                        ("secondary".into(), "217.2 32.6% 17.5%".into()),
                        ("secondary-foreground".into(), "210 40% 98%".into()),
                        ("muted".into(), "217.2 32.6% 17.5%".into()),
                        ("muted-foreground".into(), "215 20.2% 65.1%".into()),
                        ("accent".into(), "217.2 32.6% 17.5%".into()),
                        ("accent-foreground".into(), "210 40% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "210 40% 98%".into()),
                        ("border".into(), "217.2 32.6% 17.5%".into()),
                        ("input".into(), "217.2 32.6% 17.5%".into()),
                        ("ring".into(), "224.3 76.3% 48%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "yellow".into(),
            label: "Yellow".into(),
            active_color: HashMap::from([
                (Mode::Light, "47.9 95.8% 53.1%".into()),
                (Mode::Dark, "47.9 95.8% 53.1%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "20 14.3% 4.1%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "20 14.3% 4.1%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "20 14.3% 4.1%".into()),
                        ("primary".into(), "47.9 95.8% 53.1%".into()),
                        ("primary-foreground".into(), "26 83.3% 14.1%".into()),
                        ("secondary".into(), "60 4.8% 95.9%".into()),
                        ("secondary-foreground".into(), "24 9.8% 10%".into()),
                        ("muted".into(), "60 4.8% 95.9%".into()),
                        ("muted-foreground".into(), "25 5.3% 44.7%".into()),
                        ("accent".into(), "60 4.8% 95.9%".into()),
                        ("accent-foreground".into(), "24 9.8% 10%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "60 9.1% 97.8%".into()),
                        ("border".into(), "20 5.9% 90%".into()),
                        ("input".into(), "20 5.9% 90%".into()),
                        ("ring".into(), "20 14.3% 4.1%".into()),
                        ("radius".into(), "0.95rem".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "20 14.3% 4.1%".into()),
                        ("foreground".into(), "60 9.1% 97.8%".into()),
                        ("card".into(), "20 14.3% 4.1%".into()),
                        ("card-foreground".into(), "60 9.1% 97.8%".into()),
                        ("popover".into(), "20 14.3% 4.1%".into()),
                        ("popover-foreground".into(), "60 9.1% 97.8%".into()),
                        ("primary".into(), "47.9 95.8% 53.1%".into()),
                        ("primary-foreground".into(), "26 83.3% 14.1%".into()),
                        ("secondary".into(), "12 6.5% 15.1%".into()),
                        ("secondary-foreground".into(), "60 9.1% 97.8%".into()),
                        ("muted".into(), "12 6.5% 15.1%".into()),
                        ("muted-foreground".into(), "24 5.4% 63.9%".into()),
                        ("accent".into(), "12 6.5% 15.1%".into()),
                        ("accent-foreground".into(), "60 9.1% 97.8%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "60 9.1% 97.8%".into()),
                        ("border".into(), "12 6.5% 15.1%".into()),
                        ("input".into(), "12 6.5% 15.1%".into()),
                        ("ring".into(), "35.5 91.7% 32.9%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
        BaseColor {
            name: "violet".into(),
            label: "Violet".into(),
            active_color: HashMap::from([
                (Mode::Light, "262.1 83.3% 57.8%".into()),
                (Mode::Dark, "263.4 70% 50.4%".into()),
            ]),
            css_vars: HashMap::from([
                (
                    Mode::Light,
                    HashMap::from([
                        ("background".into(), "0 0% 100%".into()),
                        ("foreground".into(), "224 71.4% 4.1%".into()),
                        ("card".into(), "0 0% 100%".into()),
                        ("card-foreground".into(), "224 71.4% 4.1%".into()),
                        ("popover".into(), "0 0% 100%".into()),
                        ("popover-foreground".into(), "224 71.4% 4.1%".into()),
                        ("primary".into(), "262.1 83.3% 57.8%".into()),
                        ("primary-foreground".into(), "210 20% 98%".into()),
                        ("secondary".into(), "220 14.3% 95.9%".into()),
                        ("secondary-foreground".into(), "220.9 39.3% 11%".into()),
                        ("muted".into(), "220 14.3% 95.9%".into()),
                        ("muted-foreground".into(), "220 8.9% 46.1%".into()),
                        ("accent".into(), "220 14.3% 95.9%".into()),
                        ("accent-foreground".into(), "220.9 39.3% 11%".into()),
                        ("destructive".into(), "0 84.2% 60.2%".into()),
                        ("destructive-foreground".into(), "210 20% 98%".into()),
                        ("border".into(), "220 13% 91%".into()),
                        ("input".into(), "220 13% 91%".into()),
                        ("ring".into(), "262.1 83.3% 57.8%".into()),
                        ("chart-1".into(), "12 76% 61%".into()),
                        ("chart-2".into(), "173 58% 39%".into()),
                        ("chart-3".into(), "197 37% 24%".into()),
                        ("chart-4".into(), "43 74% 66%".into()),
                        ("chart-5".into(), "27 87% 67%".into()),
                    ]),
                ),
                (
                    Mode::Dark,
                    HashMap::from([
                        ("background".into(), "224 71.4% 4.1%".into()),
                        ("foreground".into(), "210 20% 98%".into()),
                        ("card".into(), "224 71.4% 4.1%".into()),
                        ("card-foreground".into(), "210 20% 98%".into()),
                        ("popover".into(), "224 71.4% 4.1%".into()),
                        ("popover-foreground".into(), "210 20% 98%".into()),
                        ("primary".into(), "263.4 70% 50.4%".into()),
                        ("primary-foreground".into(), "210 20% 98%".into()),
                        ("secondary".into(), "215 27.9% 16.9%".into()),
                        ("secondary-foreground".into(), "210 20% 98%".into()),
                        ("muted".into(), "215 27.9% 16.9%".into()),
                        ("muted-foreground".into(), "217.9 10.6% 64.9%".into()),
                        ("accent".into(), "215 27.9% 16.9%".into()),
                        ("accent-foreground".into(), "210 20% 98%".into()),
                        ("destructive".into(), "0 62.8% 30.6%".into()),
                        ("destructive-foreground".into(), "210 20% 98%".into()),
                        ("border".into(), "215 27.9% 16.9%".into()),
                        ("input".into(), "215 27.9% 16.9%".into()),
                        ("ring".into(), "263.4 70% 50.4%".into()),
                        ("chart-1".into(), "220 70% 50%".into()),
                        ("chart-2".into(), "160 60% 45%".into()),
                        ("chart-3".into(), "30 80% 55%".into()),
                        ("chart-4".into(), "280 65% 60%".into()),
                        ("chart-5".into(), "340 75% 55%".into()),
                    ]),
                ),
            ]),
        },
    ]
});
