[package]
name = "shadcn-ui-leptos-utils"
description = "Leptos port of shadcn/ui utils."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
# leptos.workspace = true
# tailwind_fuse.workspace = true
