[package]
name = "shadcn-ui-leptos-badge"
description = "Leptos port of shadcn/ui Badge."
homepage = "https://shadcn-ui.rustforweb.org/components/badge.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tailwind_fuse.workspace = true
leptos.workspace = true
leptos-node-ref.workspace = true
leptos-style.workspace = true