[package]
name = "scripts"
description = "Scripts for Rust shadcn/ui."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
convert_case = "0.7.0"
env_logger.workspace = true
handlebars = "6.1.0"
log.workspace = true
regex = "1.11.0"
shadcn-registry = { path = "../packages/registry" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
