[package]
name = "shadcn-ui-yew-badge"
description = "Yew port of shadcn/ui Badge."
homepage = "https://shadcn-ui.rustforweb.org/components/badge.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tailwind_fuse.workspace = true
yew.workspace = true
yew-style.workspace = true
