[package]
name = "shadcn-ui-leptos-input"
description = "Leptos port of shadcn/ui Input."
homepage = "https://shadcn-ui.rustforweb.org/components/input.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tailwind_fuse.workspace = true
leptos.workspace = true
leptos-node-ref.workspace = true
leptos-style.workspace = true
shadcn-ui-leptos-utils = { path = "../utils" }
