[package]
name = "shadcn-ui-yew-button"
description = "Yew port of shadcn/ui button."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = false
tailwind_fuse.workspace = true
