[package]
name = "shadcn-ui-yew-button"
description = "Yew port of shadcn/ui Button."
homepage = "https://shadcn-ui.rustforweb.org/components/button.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tailwind_fuse.workspace = true
yew.workspace = true
yew-struct-component.workspace = true
yew-style.workspace = true
