[package]
name = "shadcn-ui-leptos-form"
version = "0.0.0"
edition = "2021"
description = "Leptos port of shadcn/ui Form component"
license = "MIT"
repository = "https://github.com/RustForWeb/shadcn-ui"
keywords = ["leptos", "ui", "form", "validation", "shadcn"]
categories = ["wasm", "gui"]

[dependencies]
leptos = "0.8"
leptos-style = "0.2"
web-sys = { version = "0.3", features = ["HtmlFormElement", "HtmlInputElement", "HtmlElement", "Element", "Node", "Event", "EventTarget", "SubmitEvent"] }
wasm-bindgen = "0.2"
tailwind_fuse = "0.1"

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils"}
wasm-bindgen-test = { workspace = true }

[lib]
name = "shadcn_ui_leptos_form"
path = "src/lib.rs"

[[example]]
name = "form_example"
path = "examples/form_example.rs"
