name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

env:
    RUSTFLAGS: '-Dwarnings'

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy, rustfmt
                  target: wasm32-unknown-unknown

            - name: Check formatting
              run: cargo fmt --all --check

            - name: Lint
              run: cargo clippy --all-features --locked

            - name: Test
              run: cargo test --all-features --locked --release
